version: '3.8'

services:
  oracle-database-service:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-database
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - DATABASE_NAME=DEMASY
      - ORACLE_PWD=Demasy@1986

  restful-apis-service:
    build:
      context: ./
    container_name: nodjs-apis
    ports:
      - "3000:3000"
    depends_on:
      - oracle-database-service
    environment:
      - DEMASY_DB_HOST=oracle-database
      - DEMASY_DB_PORT=1521
      - DEMASY_DB_SERVICE=FREE
      - DEMASY_DB_USER=system
      - DEMASY_DB_PASS=Demasy@1986

networks:
  default:
    name: demasy-network